const Images = {
    Yumquick: require("../assets/img/yumquick.png"),
    Onboardinga: require("../assets/img/onboardinga.png"),
    Onbicon: require ("../assets/img/onbicon.png"),
    Nexticon: require("../assets/img/NexticonArrow.png"),
    
    Card1: require("../assets/img/Cardicon.png"),
    Banh:require("../assets/img/hinh-cafe.png"),
    Delivery : require("../assets/img/DeliverBoyIcon.png"),
    Launch : require("../assets/img/Launch.png"),
    BackArro: require("../assets/img/BackArrow.png"),
    Showofff:require("../assets/img/ShowOff.png"),
    Facebookicon:require("../assets/img/FacebookIcon.png"),
    Goggleicon:require("../assets/img/GoogleIcon.png"),
    FingerprintIcon:require("../assets/img/FingerprintIcon.png"),
    SearchIcon: require("../assets/Homepage/SearchIcon.png"),
    Card: require("../assets/Homepage/cart.png"),
    Noficication:require("../assets/Homepage/nofication.png"),
    People : require("../assets/Homepage/people.png"),
    SnacksIcon:require("../assets/Homepage/SnacksIcon.png"),
    MealIcon:require("../assets/Homepage/MealIcon.png"),
    VeganIcon:require("../assets/Homepage/VeganIcon.png"),
    DessertIcon:require("../assets/Homepage/DessertIcon.png"),
    DrinksIcon:require("../assets/Homepage/DrinksIcon.png"),
    SushiImage:require("../assets/Homepage/SushiImage.png"),
    PastaImage:require("../assets/Homepage/PastaImage.png"),
    Vege:require("../assets/Homepage/vegetable.png"),
    CakeImage:require("../assets/Homepage/CakeImage.png"),
    PizzaImage:require("../assets/Homepage/PizzaImage.png"),
    BurgerImage:require("../assets/Homepage/BurgerImage.png"),
    SpringRollsImage:require("../assets/Homepage/SpringRollsImage.png"),
    HeartIcon:require("../assets/Homepage/HeartIcon.png"),
    Dua:require("../assets/notification/dua.png"),
    Heart: require("../assets/notification/heart.png"),
    Khoa:require("../assets/notification/khoa.png"),
    Motorbike:require("../assets/notification/motorbike.png"),
    Notificationn:require("../assets/notification/NotificationIcon.png"),
    Noi:require("../assets/img/noi.png"),
    Vectoricon:require("../assets/img/Vector.png"),
    Heart1:require("../assets/img/heart1.png"),
    Note:require("../assets/img/note.png"),
    Listen: require("../assets/img/listen.png"),
    Rectangle: require("../assets/img/Rectangle132.png"),
    Rectangle128: require("../assets/img/Rectangle128.png"),
    Rectangle138: require("../assets/img/Rectangle138.png"),
    Dieuchinh :require("../assets/img/dieuchinh.png"),
    Addcart : require ("../assets/img/addcart.png"),




  };
  
  export default Images;
  